### ISSUE TITLE
Rock Cutter - no interface

### ISSUE THREAD

**Issue by Sevidra** [GlobbyPotato/Rockhounding_Core#1]
Have the 1.12.2 version.  Right-clicking the rock-cutting machine does nothing.

I CAN add water and lava to the machine, by right-clicking with a bucket.  Water does affect the numbers shown in Waila, so I'm assuming it's in there.  

But without access to the machine itself, I can't put in a cutting blade.

**Comment by GlobbyPotato** [comment]
Hi, I checked the machine but I can't reproduce the issue. It opens correctly here. Some info please:
Did you updated to latest versions for mod and core?
Was it a fresh install or a version update?
Did you tried to break the machine and place it again to refresh the tile?
Is there any error reported in the log file?

**Comment by Sevidra** [comment]
Should probably be moved to known conflicts or something.  I'm trying to
sort out now which mod is making it happen, as loading up with ONLY your
mods worked fine!

There IS a conflict somewhere, but thank heaven it's a gui conflict with
someone else and not a coding problem.  Give me a few and I'll tell you
which one it is

-Rachael (Sevi)

**Comment by Sevidra** [comment]
Ok I can't reproduce it in single player.  Going to start working with a
server fileset to see what it takes there.

-Rachael

**Comment by Sevidra** [comment]
Got it.

Multiplayer only.

I stripped out a bunch of mods - it IS from your mod.  It isn't functioning
properly on the MP server (and yes, latest files from December). :)

Here's the latest log to show what's going on

-Rachael

**Comment by GlobbyPotato** [comment]
yup, found it, it was a parameter accidentally being loaded from client on server. The gui was working fine so it should just open again now.
Sorry for the inconvenience.

**Comment by Sevidra** [comment]
Tested and working, thank you Globby! <3
