### ISSUE TITLE
1.12.2 Crash when placing the cutting machine

### ISSUE THREAD

**Issue by Goldobsidian** [GlobbyPotato/Rockhounding_Core#3]
Hello, I am playing with a custom mod pack in a single player world and I am constantly getting this error when I try and place the cutting machine in my world.

I noticed that there was an issue opened in december but it was closed, I have the latest editions of all of the rockhounding mods as far as im aware.

The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: INPUT_SLOTS

This is the full crash log
https://drive.google.com/file/d/1oBFnkGDFzu6-9bUnFo_vmSVf48otqeHe/view?usp=sharing

**Comment by Goldobsidian** [comment]
I just had to use MCedit to delete the machine because it wouldnt let me load my world any more with the machine placed.

**Comment by GlobbyPotato** [comment]
Hi, it looks like the module Rocks is not in sync with the Core. Try updating Rocks to v3.04.

**Comment by Goldobsidian** [comment]
Im very sorry to have wasted your time. I updated and its working fine now. I though the version numbers of each mod matching and 3.03 was the most recent for core so I didnt think one of the branches could have updated. Lesson Learned.

**Comment by GlobbyPotato** [comment]
No problem at all, glad it solved. Versions are independent to avoid reuploading copies just for version sync.
